### ISSUE TITLE
Control buttons accessible inside print dialog

### ISSUE THREAD

**Issue by hawkeyexp** [UnchartedBull/OctoDash#1453] opened 2021-02-20 18:00 UTC
Hi,

it would be nice to have access to some control buttons which are assigned to options like light on/off from case etc. - same way as the custom buttons which are currently possible while not printing.

A fourth button (addon to cancel / pause / adjust inside print dialog) which will guide to the custom buttons would be great or possible direct - the screen is big enough in most cases:-)

**Comment by UnchartedBull** [comment] 2021-03-02 10:49
duplicate of #828

**Closed by UnchartedBull** 2021-03-02 10:49 UTC
Labels: enhancement
