### ISSUE TITLE
Octodash with mutliple octoprint instances

### ISSUE THREAD

**Issue by strangecalling** [UnchartedBull/OctoDash#1651] opened 2021-04-05 18:06 UTC
Feature inqury

Can Octodash switch between Octoprint instances if it has been setup for two or more printers?

Following on from Chris' basement video "OctoPi 0.18 - Multi Printers & Cameras On 1 Pi - Chris's Basement".

It would be nice if OctoDash could switch from one octoprint instance to another without rebooting.

**Comment by UnchartedBull** [comment] 2021-04-06 09:43
duplicate of #1148.

**Closed by UnchartedBull** 2021-04-06 09:43 UTC
Labels: enhancement
