### ISSUE TITLE
E: Repository 'http://raspbian.raspberrypi.org/raspbian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'

### ISSUE THREAD

**Issue by zrox2k** [UnchartedBull/OctoDash#2233] opened 2021-09-04 18:16 UTC
**What doesn't work?**

**What did you already try?**
A clear and concise description of what you tried to make OctoDash work.

**General Information:**
 - Hardware [e.g. Raspberry Pi, if you have layout issues please also include your screen resolution]
 - OS Info [e.g. Raspbian Buster Lite, please also indicate if you used OctoPi]
 - OctoDash Version [e.g. v1.0.0]
 - OctoPrint Version [e.g. v1.0.0]

**Additional context**

**Comment by jneilliii** [comment] 2021-09-04 18:22
Run `sudo apt update` and then try running the install script again.

**Comment by jneilliii** [comment] 2021-09-04 18:22
duplicate of #2217

**Closed** 2021-09-08 21:32 UTC
Labels: support
