### ISSUE TITLE
409 conflict error

### ISSUE THREAD

**Issue by megatech1966** [UnchartedBull/OctoDash#890] opened 2020-08-08 14:39 UTC
**Describe the bug**

**To Reproduce**![image](https://user-images.githubusercontent.com/38471450/89713042-27aa7c80-d9d4-11ea-808b-5cbe4e50610b.jpeg)
1. Go to files
2. Click on local
3. Select file to print
4. See error 409 conflict. Still prints ok. 

**Expected behavior**
No error message

**Screenshots**

**General Information:**
 - Hardware pi 4. CR10S3
 - OS Info Raspbian Buster Lite
 - OctoDash Version [v2]
 - OctoPrint Version [v1.4.2]

**Additional context**

**Comment by UnchartedBull** [comment] 2020-08-10 21:57
Has this started with 1.4.2, so doesn't occur with 1.4.0? I've been away a couple of days, so I'm just catching up.

**Comment by megatech1966** [comment] 2020-08-10 23:10
Not sure. I would have to see if I can downgrade OctoPrint to 1.4.0

**Comment by megatech1966** [comment] 2020-08-14 13:39
Does not do it with OctoPrint 1.4.0

**Comment by UnchartedBull** [comment] 2020-08-18 09:18
Haven't had any time to upgrade my printer to 1.4.2 yet. I'll try to find some time this week.

**Comment by UnchartedBull** [comment] 2020-09-02 08:18
Could you maybe send over that GCode file? I can't reproduce this issue on 1.4.2 on my machine :/.

**Comment by megatech1966** [comment] 2020-09-02 14:40
I can’t get it to do it anymore. But sometimes I do get this error.

**Comment by megatech1966** [comment] 2020-09-02 14:51
I got it to do it .
https://www.dropbox.com/t/XUMcYjkUalIKvYrs

Sent from Mail for Windows 10

**Comment by UnchartedBull** [comment] 2020-09-07 09:21
Thanks. I'll try that and report back :)

**Comment by UnchartedBull** [comment] 2020-09-15 14:54
I've tried multiple things and I'm just not able to replicate this on my end. With one of the next releases the API calls will be replaced by the OctoPrint JS Client, which should hopefully fix this issue. Until then I probably won't be able to provide a fix for this. Sorry for the inconvenience. Will most likely be fixed together with #595

**Comment by titis14** [comment] 2020-09-18 20:32
Hello, I have the same error I think it came from a usb problem between my screen, the printer and the cam but apparently it's something else.
![Image of ocotdash](http://servertitis.free.fr/images/informatique/imprimante_3d/IMG_8371.jpg)

**Comment by UnchartedBull** [comment] 2020-09-21 17:25
@titis14 the error you're getting is something different. The weird thing is that the values for your printer are all available (temperature / status / ...). What happens if you close the card, does it come back again? Mabye OctoPrint just had a small hickup.

**Comment by megatech1966** [comment] 2020-09-21 18:10
Card goes away. I am going to do a fresh OctoPrint install. I will see if it still happens.

**Comment by titis14** [comment] 2020-09-21 19:38
@UnchartedBull If I type on the notification it goes away and no problem afterwards. I have to do a test without the cam because at the beginning of the installation of octodash I did not have this error.

**Comment by megatech1966** [comment] 2020-09-26 15:45
I did a fresh install of OctoPrint and octodash. Still get errors when picking gcode files. This I didn't install samba. Thought that might fix it. It didn't 🥺

**Comment by megatech1966** [comment] 2020-09-28 15:51
I think I fixed it. I was using the API key which was under the user settings. I changed it to the global API key and haven't seen that error message since.

**Comment by UnchartedBull** [comment] 2020-09-28 16:16
Great! Closing this for now. If the issue reappears please reopen :)

**Closed by UnchartedBull** 2020-09-28 16:16 UTC
Labels: bug

**Comment by titis14** [comment] 2020-09-28 16:33
Switching on the printer and octodash today I had no error.

**Comment by megatech1966** [comment] 2020-09-29 09:18
I thought I had fix the 409 error when I used the global API key, but no it still happens😢. Also tried port 80 instead of 5000. No change🥺 Tried uninstalling octopod. No change😭 Is there any else that I can try?

**Comment by megatech1966** [comment] 2020-09-29 09:19
> Switching on the printer and octodash today I had no error.

Sometimes it works. Sometimes it doesn't 🥺

**Comment by megatech1966** [comment] 2020-10-01 14:51
It's been solved by James Mackay. For some reason my touchscreen is recording 2 taps when I tap on the print icon too slowly.

**Comment by titis14** [comment] 2020-10-02 19:30
> 
> 
> > Switching on the printer and octodash today I had no error.
> 
> Sometimes it works. Sometimes it doesn't 🥺

The same for me during my last 2 ignition 409 error tap on it and it works anyway.

**Comment by megatech1966** [comment] 2020-10-02 22:15
Did you see me post? I found what was causing it. A dev on Facebook suggested it and he was right.

**Comment by titis14** [comment] 2020-10-04 19:29
> 
> Did you see me post? I found what was causing it. A dev on Facebook suggested it and he was right.
> […](#)
> Sent from my iPhone X 256Gb
> On 3 Oct 2020, at 5:01 am, titis14 ***@***.***> wrote: ﻿ Switching on the printer and octodash today I had no error. Sometimes it works. Sometimes it doesn't 🥺 The same for me during my last 2 ignition 409 error tap on it and it works anyway. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I have the error already starting without touching the screen and even without turning on the printer.

**Comment by megatech1966** [comment] 2020-10-04 22:27
You will get all sort of errors if the printer isn’t on.

**Comment by UnchartedBull** [comment] 2020-10-05 17:42
@titis14 could you maybe elaborate on the errors you're getting? Maybe attaching a screenshot. Do they also occur if the printer is turned on?

**Comment by titis14** [comment] 2020-10-05 19:35
> 
> 
> @titis14 could you maybe elaborate on the errors you're getting? Maybe attaching a screenshot. Do they also occur if the printer is turned on?

Hello, I put a screenshot above with the orange screen. I also have the error if the printer and turn on. I don't know what it came from because if I type on the message it goes away and everything works normally.

**Comment by UnchartedBull** [comment] 2020-10-09 08:13
Oh didn't saw that you're the same guy. As stated above please wait for release 2.2 or 2.3, which will replace the API with OctoPrint websocket. This should get rid of the error. Sorry that you need to close this each time until then :/

**Comment by titis14** [comment] 2020-10-10 19:26
> 
> 
> Oh didn't saw that you're the same guy. As stated above please wait for release 2.2 or 2.3, which will replace the API with OctoPrint websocket. This should get rid of the error. Sorry that you need to close this each time until then :/

No problem ;) you do a great job is for free.
