### ISSUE TITLE
Support for alternate, feature filled, filament manager Spools and some others...

### ISSUE THREAD

**Issue by cjmalchow** [UnchartedBull/OctoDash#1931] opened 2021-06-10 02:48 UTC
To start, let me thank you so much for this awesome program! It has saved me many trips running back and forwards from my computer to my printer, in another room. I'd like to ask that you look into adding support for the plugin Spools. It's a filament manager similar to Filament Manager, but it tracks more info and has many more features. I'm sure I can't be the only one that would prefer Spools.

I'd also like to see some support for Bed Visualizer. I would love to be able to start a bed visualizer tracked levelling from my OctoDash screen, as well as be able to review the recommended adjustments to the knobs to achieve near perfect levelling. As it stands I have to take pictures, or sketch/write down the suggested adjustments, it would be awesome to be able to do this from the OctoDash screen. The only issue I could see there being is that clicking on any of the adjustment numbers results in it recalculating all the adjustments around that specific point.

Thanks for all you do!

Cameron

**Comment by UnchartedBull** [comment] 2021-06-16 08:36
duplicate of #676.

duplicate of #1002.

**Closed by UnchartedBull** 2021-06-16 08:36 UTC
Labels: enhancement
