### ISSUE TITLE
Access controls during pause

### ISSUE THREAD

**Issue by pciavald** [UnchartedBull/OctoDash#1753] opened 2021-05-03 10:00 UTC
**Is your feature request related to a problem? Please describe.**

When pausing a print, it's currently impossible to manually control the printer. During a print, we had to cancel the print to solve a clogged head, which could have been done during the pause.

**Describe the solution you'd like**

Allow access to print controls on the pause screen

**Comment by UnchartedBull** [comment] 2021-05-03 11:35
duplicate of #828

**Closed by UnchartedBull** 2021-05-03 11:35 UTC
Labels: enhancement

**Comment by pciavald** [comment] 2021-05-03 11:58
Can you help me understand how accessing the controls from the pause screen is related to the mentioned issue, that seems more about having more control on the control screen's buttons ?

**Comment by UnchartedBull** [comment] 2021-05-03 12:04
You would have full access to the control screen while paused (so the arrow to move the tool around and all Custom Actions). This is all the manual controls OctoDash does offer.
