### ISSUE TITLE
Add possibility for manual bed leveling

### ISSUE THREAD

**Issue by yemu** [UnchartedBull/OctoDash#1228] opened 2020-12-03 10:05 UTC
Hi,
Live octoDash, after using it for couple of days I find the manual bed leveling missing. It would be great if OctoDash would include this option similar to eg. Bed Levelling Wizard Plugin.

Best 
Y

**Comment by UnchartedBull** [comment] 2020-12-08 09:37
Duplicate of #312.

**Closed by UnchartedBull** 2020-12-08 09:37 UTC
