### ISSUE TITLE
initializing - Can't get octoprint script

### ISSUE THREAD

**Issue by jaymcd** [UnchartedBull/OctoDash#1153] opened 2020-11-03 15:21 UTC
Since upgrading to v2.11 I am getting an initialization error that says "can't get octoprint script" so Octodash won't startup. I have re-installed using the wget script to no avail.

**Comment by UnchartedBull** [comment] 2020-11-03 17:01
duplicate of #1097. I'm working on a fix.

**Closed by UnchartedBull** 2020-11-03 17:01 UTC
Labels: bug
