### ISSUE TITLE
Support Multiple Extruder / Tool heads

### ISSUE THREAD

**Issue by jim-edwards** [UnchartedBull/OctoDash#1489] opened 2021-02-25 03:41 UTC
The UI currently only lists the first extruder on a multi-extruder system.  The main screen should show all the extuders on the main screen and allow temperature control.  The control screen should allow switch the active head and then move it around.

For example, from the main UI:
![image](https://user-images.githubusercontent.com/1817474/109099496-70abef00-76e0-11eb-86ce-eb8c0a679d2b.png)

The change tool from the controls:
![image](https://user-images.githubusercontent.com/1817474/109099568-8b7e6380-76e0-11eb-8233-16e993839e90.png)

Example display from the "Dashboard" plugin:
![image](https://user-images.githubusercontent.com/1817474/109099619-9df89d00-76e0-11eb-8bc7-24d7d5d99b17.png)

**Comment by UnchartedBull** [comment] 2021-03-02 09:58
Duplicate of #779. Might become something in the future, there are no plans regarding Dual Extruder support atm. Open to PRs though.

**Closed by UnchartedBull** 2021-03-02 09:58 UTC
Labels: enhancement
