### ISSUE TITLE
Need input method for Settings -> General

### ISSUE THREAD

**Issue by Jozer99** [UnchartedBull/OctoDash#1894] opened 2021-06-02 18:57 UTC
In the Settings menu, the General section has several text and numerical fields.  There is no method for entering text or numbers into these fields.  An onscreen keyboard or "up/down" arrows would be useful here.

**Comment by UnchartedBull** [comment] 2021-06-07 09:03
Duplicate of #762. You can also use the OctoDash Companion App.

**Closed by UnchartedBull** 2021-06-07 09:03 UTC
Labels: enhancement
