### ISSUE TITLE
IP address on main screen

### ISSUE THREAD

**Issue by scottamoulton** [UnchartedBull/OctoDash#1320] opened 2021-01-20 22:31 UTC
I would like to request to add the ip address at the open blank space in the middle of the screen on the display.

**Comment by UnchartedBull** [comment] 2021-01-23 12:43
duplicate of #1202. please see linked issue for more details. The blank space in the middle is used for ambient temperature (if configured)

**Closed by UnchartedBull** 2021-01-23 12:43 UTC
Labels: enhancement
