### ISSUE TITLE
Can't retrieve layer progress!

### ISSUE THREAD

**Issue by KD305** [UnchartedBull/OctoDash#1521] opened 2021-03-04 20:59 UTC
I have a Prusa Mk3 with a raspberry pi connected. Octoprint has been installed and is working, including webcam streaming.
I have also installed octodash so i can use the pi official 7" touchscreen
![IMG_6343](https://user-images.githubusercontent.com/80069364/110029395-53080680-7d2c-11eb-89d6-572ac5ddf2c2.jpeg)
.

It seems to be nearly there, octodash is showing up on the screen but just keeps showing a message  Can't retrieve layer progress!

I have already read the previous posts but am not too adept when it comes with coding. Octoprint did get the request sent from octodash and both octoprint and octodash commands will control the printer. It just seems to be this message which wont dissapear from the touchscreen.

I tried changing the port to 5000 but then it would not connect at all, ended up just sitting on connecting... indefinitely. I figured out how to SSH into the PI and ran rm .config/octodash/config.json to get it back to a state where some settings could be changed on the touch screen.

I am guessing it is something simple i have missed out but would be grateful for any help.

**Comment by UnchartedBull** [comment] 2021-03-05 14:41
duplicate of #1304. v3 will fix this, until then please install the version from the linked fork in the other issue.

**Closed by UnchartedBull** 2021-03-05 14:41 UTC
Labels: support
