### ISSUE TITLE
Fan adjustment during print

### ISSUE THREAD

**Issue by beef76** [UnchartedBull/OctoDash#1087] opened 2020-10-16 18:54 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. If applicable also link other issues / bugs here.
Not related to an open issue

**Describe the solution you'd like**
Coming from Repetier Server and it's Pi Screen i'm missing a lot, however not everything is that much missed like the adjustment of Fan Speed during prints.
It's sad too that there is not any possibility out of the box on the web interface. Just with adding special buttons with Gcode behind it's possible.

**Link other projects**
If you want OctoDash to include other OctoPrint plugins or similar please link them here.

**Additional context**

**Comment by UnchartedBull** [comment] 2020-10-19 15:24
Duplicate of #841. Will be released with v2.1.0.

**Closed by UnchartedBull** 2020-10-19 15:24 UTC
Labels: enhancement
