### ISSUE TITLE
v2.2.0 update problems (LC_ALL: cannot change local | Stuck at initialization)

### ISSUE THREAD

**Issue by jasonmacdonald** [UnchartedBull/OctoDash#1818] opened 2021-05-18 14:15 UTC
**Describe the bug**
Trying to update via the UI results in a failure with the error `Can't install update!` with the warning `/bin/bash:warning: setlocale: LC_ALL: cannot change locale (en-GB)`

**To Reproduce**
1. Click update

**Expected behavior**
Should update

**General Information:**
 - Raspberry Pi 4b
 -OctoPi
 - OctoDash Version 2.1.2

**Comment by RNRMentor** [comment] 2021-05-18 14:25
Same issue.  Completed manual update, but now stuck at initializing after reboot. Issue is persistent after multiple reboots.

**Comment by sergejvoronov** [comment] 2021-05-18 14:32
same here.

**Comment by elictes** [comment] 2021-05-18 14:58
I also have this issue.

**Comment by fredlex3dprints** [comment] 2021-05-18 15:19
same issue

**Comment by fredlex3dprints** [comment] 2021-05-18 15:33
I got same issue. Updated it in the app and got the error.
put power off and back on. Octodash started normally with the V2.2.0 installed.

**Comment by jasonmacdonald** [comment] 2021-05-18 15:36
> I got same issue. Updated it in the app and got the error.
> put power off and back on. Octodash started normally with the V2.2.0 installed.

I tried this and now I'm stuck on initializing screen like @RNRMentor

**Comment by RNRMentor** [comment] 2021-05-18 15:41
> > I got same issue. Updated it in the app and got the error.
> > put power off and back on. Octodash started normally with the V2.2.0 installed.
> 
> I tried this and now I'm stuck on initializing screen like @RNRMentor

I ended up using the uninstall script and did a clean install of OctoDash.  Now everything is working.  I did not explore further, but I suspect that the initialization error may be due to CORS not being enabled?

**Comment by UnchartedBull** [comment] 2021-05-18 15:51
The LC_ALL error is due to a misconfigured `locale` (most likely not set at all): https://raspberrypi.stackexchange.com/questions/43550/unable-to-reconfigure-locale-in-raspberry-pi. 

The stuck on initialisation error is due to CORS not being enabled in the API Section (OctoPrint Settings)

**Comment by Sil3ntLight** [comment] 2021-05-18 16:05
I can confirm this fix. After upgrade, when stuck on initialization screen, go into OctoPrint -> settings -> API, and make sure the Allow CORS checkbox is checked. Then reboot.

**Comment by csprocket777** [comment] 2021-05-18 16:06
I already had that checked, update issue still remains for me.

**Comment by UnchartedBull** [comment] 2021-05-18 16:29
So you're still stuck on the initialization screen @csprocket777?

**Comment by csprocket777** [comment] 2021-05-18 16:40
Correct. This is what I'm seeing. ![image](https://user-images.githubusercontent.com/4195745/118690647-dd112880-b7cd-11eb-827d-385835d83999.jpeg)

**Comment by UnchartedBull** [comment] 2021-05-18 16:43
Ah ok, that's the update error. If you fixed your `locale` this error should go away, but if it's still appearing please try the manual update script.

**Comment by csprocket777** [comment] 2021-05-18 16:45
I thought I had my locale set. How should I check this?

**Comment by jasonmacdonald** [comment] 2021-05-18 16:51
I had my local set, but I redid it to what was in the forum post on https://raspberrypi.stackexchange.com/questions/43550/unable-to-reconfigure-locale-in-raspberry-pi and on restart that finally fixed the error. No clue why the en-GB that I already had uncommented wasn't working. But, doing the `locale-gen` and  `update-locale` seems to have resolved it

**Comment by NovaViper** [comment] 2021-05-18 16:57
I had to follow this answer in order to get it working: https://raspberrypi.stackexchange.com/a/81765

**Comment by UnchartedBull** [comment] 2021-05-18 17:19
@csprocket777 by following the links posted here and checking whether your file look alright. If you don't feel like this, the manual update is still an option though.

@ all Thanks for posting your tips here for other users! I'm going to keep this issue open and pinned for a week or two :). Feel free to post further findings if you have any!

**Comment by forrest-eyles** [comment] 2021-05-18 17:40
I followed everything here it its up and running again thank everyone.

**Comment by csprocket777** [comment] 2021-05-18 17:48
Followed the same answer as @NovaViper  and once OctoDash rebooted, everything worked.

**Comment by psebening** [comment] 2021-05-20 09:13
I was stuck on the initializing screen after rebooting because I also had the LC_ALL Update Error. I did restart octoprint in Safe Mode, activated the CORS API in the Settings and update the locale as told in the above stackexchange links. Everything is running smoothly again now :)

**Comment by Qualith** [comment] 2021-05-22 10:54
Same problem here.

Finally I fixed it just by running via ssh the update script.
wget -qO- https://github.com/UnchartedBull/OctoDash/raw/main/scripts/update.sh | bash

**Comment by UnchartedBull** [comment] 2021-06-01 12:16
I think most people upgraded by now (almost 4k downloads!). So I'm closing this here now. Sorry for all the hassle with the upgrade.

**Closed by UnchartedBull** 2021-06-01 12:16 UTC
Labels: support
