### ISSUE TITLE
add brightness adjustment

### ISSUE THREAD

**Issue by ssavickiy** [UnchartedBull/OctoDash#1292] opened 2021-01-09 21:48 UTC
there are not enough settings for the display brightness (backlight) and the option to completely turn off the backlight. Here is an implementation,
https://github.com/linusg/rpi-backlight

I have BIGTREETECH PITFT50 V1.0 installed and in idle moments, the display turns black, but the backlight still lights up.

**Comment by UnchartedBull** [comment] 2021-01-12 10:05
duplicate of #410. Already partially done (see last comment in linked issue)

**Closed by UnchartedBull** 2021-01-12 10:05 UTC
Labels: duplicate
