### ISSUE TITLE
octodash not working properly

### ISSUE THREAD

**Issue by dmitrimedina** [UnchartedBull/OctoDash#1994] opened 2021-06-25 23:09 UTC
**Describe the bug**
today I begin a print via the octoprint web on my laptop, I have a raspberry pi 3b+ running octoprint and octodash and I notice that on the octoprint web everything its running normal with the print in this right moment but on the raspberry the octodash its only showing the home menu where its say files, filament and setting its not showing the actual print that its happening right now. but in the right corner on the bottom on the octodash its say printing

**Expected behavior**
to se what aim printing on the octodash

**Comment by UnchartedBull** [comment] 2021-06-26 16:03
duplicate of #1887.

**Closed by UnchartedBull** 2021-06-26 16:03 UTC
Labels: bug
